
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: spring-boot-app
spec:
  selector:
    app: spring-boot-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000